#include QMK_KEYBOARD_H

enum {
  U_TD_BOOT,
};
void u_td_fn_boot(tap_dance_state_t *state, void *user_data) {
  if (state->count == 2) {
    reset_keyboard();
  }
}

tap_dance_action_t tap_dance_actions[] = {
    [U_TD_BOOT] = ACTION_TAP_DANCE_FN(u_td_fn_boot),
};

enum LAYERS{
  BASE,
  NAVIGATION,
  MOUSE,
  MEDIA,
  NUMBERS,
  SYMBOLS,
  FUNCTION,
  BUTTON
};
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  /*
[BASE] = LAYOUT_planck_mit(
			   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
			   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
			   
			   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
			   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
			   
			   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
			   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
			   
			   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
			   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
  */

[BASE] = LAYOUT_planck_mit(
	KC_QUOTE, KC_COMMA, KC_DOT, KC_P, KC_Y, KC_NO, KC_NO, KC_F, KC_G, KC_C, KC_R, KC_L, 
	LGUI_T(KC_A), LALT_T(KC_O), LCTL_T(KC_E), LSFT_T(KC_U), KC_I, KC_NO, KC_NO, KC_D, LSFT_T(KC_H), LCTL_T(KC_T), LALT_T(KC_N), LGUI_T(KC_S), 
	LT(BUTTON, KC_SEMICOLON), RALT_T(KC_Q), KC_J, KC_K, KC_X, KC_NO, KC_NO, KC_B, KC_M, KC_W, RALT_T(KC_V), LT(BUTTON, KC_Z), 
	KC_NO, KC_NO, LT(MEDIA, KC_ESCAPE), LT(NAVIGATION, KC_SPACE), LT(MOUSE, KC_TAB), KC_NO, LT(SYMBOLS, KC_BACKSPACE), LT(NUMBERS, KC_SPACE), LT(FUNCTION, KC_DELETE), KC_NO, KC_NO
			   ),

[NAVIGATION] = LAYOUT_planck_mit(
	TD(U_TD_BOOT), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_AGIN, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO, 
	KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_NO, CW_TOGG, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, 
	KC_NO, KC_RALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INS, KC_HOME, KC_PGDN, KC_PGUP, KC_END, 
	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_ENT, KC_TAB, KC_NO, KC_NO
	),
[MOUSE] = LAYOUT_planck_mit(
	TD(U_TD_BOOT), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_AGIN, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO, 
	KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, 
	KC_NO, KC_RALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, 
	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN2, KC_BTN1, KC_BTN3, KC_NO, KC_NO 
	),
[MEDIA] = LAYOUT_planck_mit(
	TD(U_TD_BOOT), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI, 
	KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, 
	KC_NO, KC_RALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, OU_AUTO, KC_NO, KC_NO, KC_NO, KC_NO, 
	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MSTP, KC_MPLY, KC_MUTE, KC_NO, KC_NO 
	),
[NUMBERS] = LAYOUT_planck_mit(
	KC_LBRC, KC_7, KC_8, KC_9, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TD(U_TD_BOOT), 
	KC_SLSH, KC_4, KC_5, KC_6, KC_EQL, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, 
	KC_GRV, KC_1, KC_2, KC_3, KC_BSLS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RALT, KC_NO, 
	KC_NO, KC_NO, KC_DOT, KC_0, KC_MINS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
[SYMBOLS] = LAYOUT_planck_mit(
	KC_LCBR, KC_AMPR, KC_ASTR, KC_LPRN, KC_RCBR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TD(U_TD_BOOT), 
	KC_QUES, KC_DLR, KC_PERC, KC_CIRC, KC_PLUS, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, 
	KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_PIPE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RALT, KC_NO, 
	KC_NO, KC_NO, KC_LPRN, KC_RPRN, KC_UNDS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO 
	),
[FUNCTION] = LAYOUT_planck_mit(
	KC_F12, KC_F7, KC_F8, KC_F9, KC_PSCR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TD(U_TD_BOOT), 
	KC_F11, KC_F4, KC_F5, KC_F6, KC_SCRL, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, 
	KC_F10, KC_F1, KC_F2, KC_F3, KC_PAUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ALGR, KC_NO, 
	KC_NO, KC_NO, KC_APP, KC_SPC, KC_TAB, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
	),
[BUTTON] = LAYOUT_planck_mit(
	KC_UNDO, KC_CUT, KC_COPY, KC_PSTE, KC_AGIN, KC_NO, KC_NO, KC_AGIN, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO, 
	KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, 
	KC_UNDO, KC_CUT, KC_COPY, KC_PSTE, KC_AGIN, KC_NO, KC_NO, KC_AGIN, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO, 
	KC_NO, KC_NO, KC_BTN3, KC_BTN1, KC_BTN2, KC_NO, KC_BTN2, KC_BTN1, KC_BTN3, KC_NO, KC_NO
	),

};


const uint16_t PROGMEM C_R_SPACE[] = { LSFT_T(KC_H), LCTL_T(KC_T), COMBO_END};
const uint16_t PROGMEM C_R_TAB[] = { LSFT_T(KC_H), LALT_T(KC_N), COMBO_END};
const uint16_t PROGMEM C_R_ENTER[] = { LSFT_T(KC_H), LGUI_T(KC_S), COMBO_END};
const uint16_t PROGMEM C_R_BACKSPACE[] = { KC_M, KC_W, COMBO_END};
const uint16_t PROGMEM C_R_DELETE[] = { KC_M, RALT_T(KC_V), COMBO_END};
const uint16_t PROGMEM C_R_ESCAPE[] = { KC_M, LT(BUTTON, KC_Z), COMBO_END};
const uint16_t PROGMEM C_L_SPACE[] = { LSFT_T(KC_U), LCTL_T(KC_E), COMBO_END};
const uint16_t PROGMEM C_L_TAB[] = { LSFT_T(KC_U), LALT_T(KC_O), COMBO_END};
const uint16_t PROGMEM C_L_ENTER[] = { LSFT_T(KC_U), LGUI_T(KC_A), COMBO_END};
const uint16_t PROGMEM C_L_BACKSPACE[] = { KC_K, KC_J, COMBO_END};
const uint16_t PROGMEM C_L_DELETE[] = { KC_K, RALT_T(KC_Q), COMBO_END};
const uint16_t PROGMEM C_L_ESCAPE[] = { KC_K, LT(BUTTON, KC_SCLN), COMBO_END};

combo_t key_combos[] = {
	COMBO(C_R_SPACE, KC_SPACE),

	COMBO(C_R_TAB, KC_TAB),
	COMBO(C_R_ENTER, KC_ENTER),
	COMBO(C_R_BACKSPACE, KC_BACKSPACE),
	COMBO(C_R_DELETE, KC_DELETE),
	COMBO(C_R_ESCAPE, KC_ESCAPE),
	COMBO(C_L_SPACE, KC_SPACE),
	COMBO(C_L_TAB, KC_TAB),
	COMBO(C_L_ENTER, KC_ENTER),
	COMBO(C_L_BACKSPACE, KC_BACKSPACE),
	COMBO(C_L_DELETE, KC_DELETE),
	COMBO(C_L_ESCAPE, KC_ESCAPE),

	};


